### ISSUE TITLE
TypeError occurred when I try to load my keyboard definition.

### ISSUE THREAD

**Issue by kndol** [the-via/releases#243] opened 2023-02-04 12:17 UTC
I use Keychron K8 Pro.
Previously, VIA worked well, but running the program today is causing problems.
I attempted to load a keyboard definition provided by the vendor that had worked previously, but encountered an error today:
```
TypeError: Cannot read properties of undefined (reading 'Split')
```

**Comment by wilba** [comment] 2023-02-04 13:17
Sounds like the keyboard definition is invalid according to the stricter validation that just went into VIA.
All keyboard definitions in the Github repo pass validation, some after fixing mistakes.
Since some Keychron keyboard definitions are not in the repo, we can't fix the mistakes.

See https://github.com/the-via/app/issues/91

**Comment by jg314** [comment] 2023-02-04 17:56
I also wasn't able to get the K8 Pro to work with VIA on Windows 11. I'm new to VIA, but tried toggling on `Use V2 definitions (deprecated)` and uploading the Keychron provided JSON file. I get the same error:

`TypeError: Cannot read properties of undefined (reading 'split')`

Hopefully Keychron releases a fix for this issue soon.

**Comment by Flow1392** [comment] 2023-02-04 18:31
Hi all, i've got an ISO K8 Pro since few days. It worked well with VIA software and JSON file from Keychron website. I have been able to edit some function keys and/or to add macros. But I've retried few minutes ago, does not work anymore. i've got the same error message ... very strange. Something has been released at VIA side which is no more compatible with previous JSON format ?
I really hopes a solution will be found soon

**Comment by karkianish** [comment] 2023-02-04 23:12
same issue in my case as well for K8 pro. I tried using the via app 2.1.0 in both mac and windows. Is there a way to rollback to previous versions?

**Comment by joihn** [comment] 2023-02-05 09:55
apparently the desktop app on linux just load content from this url `https://usevia.app/#/test`, which probably has been recently updated, thus breaking the K8 pro json file.
It's frustrating not to be able to manually rollback, I wish this app worked fully offline for a more granular control over it's versionning.

**Comment by kndol** [comment] 2023-02-05 13:13
> 

Previously, the JSON file was working correctly, but no longer lately.

**Comment by Flow1392** [comment] 2023-02-05 18:17
Hello,
Someone has proposed me a solution on the Facebook group of Keychron users which was : « You just need to remove all the "a" in the json file and import again. »
I confirm it works and now I can customise again my keyboard !

**Comment by karkianish** [comment] 2023-02-05 18:52
@Flow1392  - Thank-you, that worked! I had to remove the "a" from two places.

**Comment by kndol** [comment] 2023-02-06 05:28
> Hello, Someone has proposed me a solution on the Facebook group of Keychron users which was : « You just need to remove all the "a" in the json file and import again. » I confirm it works and now I can customise again my keyboard !

Thank you for the solution!

**Comment by jg314** [comment] 2023-02-12 22:18
After talking with the Keychron support team, they've confirmed that they fixed the error we were seeing. You can now download the working JSON files at https://www.keychron.com/products/keychron-k8-pro-qmk-via-wireless-mechanical-keyboard. I tested the RGB version and it worked perfectly.

**Comment by jmd-au** [comment] 2023-02-16 01:12
Just commenting to follow and get updates - as I'm getting a slightly different error when trying to import the file into VIA on a Mac. "Object: should NOT have additional properties". If anyone has seen this error before - i'd be interested to know if you've found a fix.

**Comment by wilba** [comment] 2023-02-16 04:44
Can you link to the file please?

**Comment by YodaLightsabr** [comment] 2023-02-17 08:52
> Just commenting to follow and get updates - as I'm getting a slightly different error when trying to import the file into VIA on a Mac. "Object: should NOT have additional properties". If anyone has seen this error before - i'd be interested to know if you've found a fix.

@jmac-digital I had that error message when I tried it. Redownloading and using V2 definitions fixed it for me.

> Can you link to the file please?

@wilba For the K8, here are the current [white](https://cdn.shopify.com/s/files/1/0059/0630/1017/files/k8_pro_ansi_white_v1.1.json.zip?v=1675664147) and [RGB](https://cdn.shopify.com/s/files/1/0059/0630/1017/files/k8_pro_ansi_rgb_v1.7.json.zip?v=1675664147) files.

**Comment by wilba** [comment] 2023-02-17 23:23
This works when using "Use V2 definitions"

**Closed by wilba** 2023-02-17 23:23 UTC

**Comment by nek0pi** [comment] 2023-02-25 02:24
Same problem here, using Libra mini 40% keyboard. Trying to load the V2 definition, worked previously and now I only see these errors here:
![image](https://user-images.githubusercontent.com/53343285/221331305-fa4bd4cf-e77a-4041-8b88-d93171dfd3d2.png)

I imagine this could be due to some change on the structure of the json expected or new stricter json parser in use.
Help would be highly appreciated! 

For SEO: "Should not have additional properties", "Libra Mini"
UPD: So apparently additional keymap layout and fields  "vendorIdBk" ,"productIdBk" should now go for via to work

**Comment by wilba** [comment] 2023-02-25 03:30
upload the file that doesn't work

**Comment by DjordjeMancic97** [comment] 2023-03-01 17:50
@wilba Here is JSON for Keychron Q1 Version 2, it throws same error as posted by @nek0pi 
Github does not allow sending json files as attachment so I posted it here https://pastebin.com/E9iYCULm

**Comment by wilba** [comment] 2023-03-01 23:58
This is a V3 definition, so turn off "Use V2 definitions (deprecated)" when loading

**Comment by DjordjeMancic97** [comment] 2023-03-02 16:33
> This is a V3 definition, so turn off "Use V2 definitions (deprecated)" when loading

In that case there is no errors, however nothing happens. Its searching for devices indefinitely... Could it be that json config is faulty? Should I contact keychron?

**Comment by ykolloch** [comment] 2023-03-06 15:26
@DjordjeMancic97 i got the same behavior. Do u have any update?

**Comment by DjordjeMancic97** [comment] 2023-03-06 17:12
> @DjordjeMancic97 i got the same behavior. Do u have any update?

Nothing.. will write to keychron

**Comment by jim3108** [comment] 2023-07-06 18:09
I found that under the customKeycodes array there was one which had the property 'shortName' listed as "shortName in macOS" instead of just "shortName" where "in macOS" was supposed to be at the end of the 'title' property.
