### ISSUE TITLE
Version 1.3.1 Mac dmg has Nukespeed trojan

### ISSUE THREAD

**Issue by phuturemnky** [the-via/releases#203] opened 2022-07-10 12:39 UTC
<img width="899" alt="Screenshot 2022-07-10 at 13 39 20" src="https://user-images.githubusercontent.com/109027486/178145243-c3a3045c-c2f0-4656-801f-24a1e4c6132d.png">

**Comment by olivia** [comment] 2022-07-10 15:29
Hi phuturemnky, thank you for filing an issue! I've uploaded the most recent dmg (`via-1.3.1-mac.dmg`) onto www.virustotal.com and received this [report](https://www.virustotal.com/gui/file/d7b9f6fd97cc920cebae8b92417c24f5b78856b8f2fc8512093b2fbfc9302e67/detection/f-d7b9f6fd97cc920cebae8b92417c24f5b78856b8f2fc8512093b2fbfc9302e67-1656824137) which yields 0 detections of anything malicious.

Given that your account was created today and the results that I've received I will be closing this issue for now. If you are able to provide means to being able to replicate this result, I am happy to reopen it.

**Closed by olivia** 2022-07-10 15:29 UTC

**Comment by cglmrfreeman** [comment] 2022-08-06 04:55
@olivia You might have missed #187, which also makes this claim. Considering there is a new release however, I am doubting the issue is present in it, however VIA as an application may be a target for Nukespeed trojan to do whatever it is it's doing.
