### ISSUE TITLE
Unable to create a macro on M60-A

### ISSUE THREAD

**Issue by mikecoop** [the-via/releases#3] opened 2020-01-28 20:45 UTC
I'm trying to create a macro for my M60-A but when I enter a chord in the specified format I get an error. It's quite possible I'm doing something wrong but I'm not completely sure.

<img width="761" alt="sshot-5" src="https://user-images.githubusercontent.com/1671683/73303827-17c00d80-41e5-11ea-98eb-60de102cbbc3.png">

Also, are you accepting contributions?

**Comment by stevefulghum** [comment] 2020-02-01 16:21
I'm having a similar problem with the Rama M10-B. I'm able to create macros, but using basic keycodes in the format provided fails. When the macro is applied, the key tester only registers the left shift, underscore, and enter keys being pressed:
![Annotation 2020-02-01 104740](https://user-images.githubusercontent.com/3833102/73595181-936ed280-44e3-11ea-801d-f00e94041ab9.png)
This is when using a macro with a keycode entered as so:
![Annotation 2020-02-01 1047402](https://user-images.githubusercontent.com/3833102/73595205-c9ac5200-44e3-11ea-83cc-55efb9ec31f5.png)
For reference, here is how the macros are output in JSON:
![Annotation 2020-02-01 111430](https://user-images.githubusercontent.com/3833102/73595220-09733980-44e4-11ea-8f84-2d4b4eb5578f.png)


@mikecoop , It looks like you and I are trying to make similar macros. I was trying to create a macro for LWIN+LSHIFT+LEFT/RIGHT to move windows around. What did work for me was using the "Any" button and the string LGUI(LSFT(KC_LEFT)). You might try LCTL(KC_D)

**Comment by Wilba6582** [comment] 2020-02-02 05:26
@mikecoop your problem is due to spaces in between keycodes. This is something we can fix.

@stevefulghum I am able to make macros using KC_LGUI and KC_LEFT etc. Can you try flashing the M10-B with the latest firmware from https://caniusevia.com/docs/download_firmware/ and using latest VIA ?

**Comment by stevefulghum** [comment] 2020-02-02 14:54
@Wilba6582 The updated firmware worked great. Thanks!

**Comment by mikecoop** [comment] 2020-02-02 16:16
@Wilba6582 I'll try that, thanks!

**Comment by JL276** [comment] 2020-03-13 03:16
I have an m10-b as well. I've tried flashing multiple times and the problem still persists.

I can't add any macros, and it basically is the issue described above by stevefulghum.

The flashing process for me is this:
1. Plug in m10
2. Poke reset button whilst having qmk toolkit up
3. Flash with wilba_tech_rama_works_m10_b_via.hex
4. Reconnect

The issue persists. Trying to add a macro like ctrl, or ANY key doesn't work.

**Comment by Wilba6582** [comment] 2020-03-13 03:43
@JL276 please download and install the latest VIA to make sure this isn't the problem, and also download the latest firmware from https://caniusevia.com/docs/download_firmware and install this. I want to make sure the problem is definitely not due to old firmware or old VIA version.

Can you also give me the exact text you are putting into the macro editor?

**Comment by JL276** [comment] 2020-03-13 03:54
@Wilba6582 Hi Wilba, thanks for the quick reply.

Latest VIA is installed (1.2.5 in the settings)
Downloaded m10-b.hex from that link, it's named wilba_tech_rama_works_m10_b_via.hex and is 45.8mb

Editing macro 0, with one of the keys rebound to macro 0 to activate. 

Some commands I tried:
`{KC_LGUI} `
(shows nothing pressed on key tester)

`{KC_LCTL,KC_A} `
(shows left shift pressed on key tester)

`{KC_SPC} `
(nothing)

`{KC_TAB} `
(nothing)

Tried using something other than macro 0 as well. No dice.

**Comment by Wilba6582** [comment] 2020-03-13 10:13
@JL276 OK I can reproduce this on M10-B and even getting non-working macros on M6-B as well but actually wrong in a different way... Really confused now, other PCBs are working fine and the only difference is the switch matrix.

**Comment by Wilba6582** [comment] 2020-03-13 12:22
@JL276 nevermind, it was broken for all PCBs.

Fixed now. https://github.com/qmk/qmk_firmware/pull/8407

Download latest firmware again from https://caniusevia.com/docs/download_firmware and it should work.

**Comment by JL276** [comment] 2020-03-13 12:30
Confirmed fixed. Thanks for the quick and speedy response!

**Comment by Wilba6582** [comment] 2020-03-13 12:35
Thank you for finding it!

**Closed** 2020-03-13 12:35 UTC
