### ISSUE TITLE
Via application doesn't load, remains on a white screen.

### ISSUE THREAD

**Issue by sadlesbian** [the-via/releases#234] opened 2022-12-28 06:16 UTC
Downloaded it initially a few days ago and it worked; now after relaunching the software for the first time since it flashes black for a frame and stops on an all white screen. Can only find one other post in the issues section on this GitHub talking about it to no resolution. Any clue on what the problem is / if there's a fix?

**Comment by melonaicebar** [comment] 2022-12-28 08:13
I'm also having the same issue:(

**Comment by ForsakenRei** [comment] 2022-12-28 21:40
Same here, just installed latest 2.0.5

**Comment by ValdisThomann** [comment] 2023-02-05 14:03
Duplicate of #233

**Closed by ValdisThomann** 2023-02-05 14:03 UTC
